dist: trusty
sudo: false

language: go

env:
jobs:
  include:
    # YAML alias, for settings shared across the tests
    - stage: test
      go: 1.8
      install:
        - true
      script:
        - true

    - stage: deploy
      go_import_path:  github.com/redhat-developer/ocdev
      go: 1.9
      install:
        - env
      script: skip
      before_deploy:
        - true
      deploy:
        # upload binaries to bintray
        - provider: script
          script:
            - echo "on master"
          skip_cleanup: true
          on:
            on: master
        # upload gziped binaries to github release page
        - provider: script
          script:
            - echo "on tags"
          skip_cleanup: true
          on:
            tags: true
        # upload packages to bintray repositories
        - provider: script
          skip_cleanup: true
          script:
            - echo "on master2"
          on:
            # run this on tag and on master
            branch: master
        - provider: script
          skip_cleanup: true
          script:
            - echo "on tags"
          on:
            # run this on tag and on master
            tags: true